# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-03-04T19:54:58+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, EmailStr, Field


class Status(Enum):
    placed = 'placed'
    approved = 'approved'
    delivered = 'delivered'


class Order(BaseModel):
    id: Optional[int] = Field(None, description='Id of the order.', example=10)
    petId: Optional[int] = Field(None, description='PetId', example=198772)
    quantity: Optional[int] = Field(None, description='Quantity', example=7)
    shipDate: Optional[datetime] = Field(
        None, description='Shipping date.', example='2017-07-21T17:32:28Z'
    )
    status: Optional[Status] = Field(
        None, description='Order Status', example='approved'
    )
    complete: Optional[bool] = Field(None, description='Order completed.', example=True)


class Category(BaseModel):
    id: Optional[int] = Field(None, description='Id', example=1)
    name: Optional[str] = Field(None, description='Name of category.', example='Dogs')


class User(BaseModel):
    id: Optional[int] = Field(None, description='Id', example=10)
    username: Optional[str] = Field(None, description='Username', example='theUser')
    firstName: Optional[str] = Field(None, description='First name', example='John')
    lastName: Optional[str] = Field(None, description='Last name', example='James')
    email: Optional[EmailStr] = Field(
        None, description='User mail address.', example='john@email.com'
    )
    password: Optional[str] = Field(None, description='Password.', example='password')
    phone: Optional[str] = Field(None, description='Phone number', example='012345')
    userStatus: Optional[int] = Field(None, description='User Status', example=1)


class Tag(BaseModel):
    id: Optional[int] = Field(None, description='Id', example=1)
    name: Optional[str] = Field(None, description='Name of tag.', example='tag1')


class Status1(Enum):
    available = 'available'
    pending = 'pending'
    sold = 'sold'


class Pet(BaseModel):
    id: Optional[int] = Field(None, description='Id', example=10)
    name: str = Field(..., description='Name', example='doggie')
    category: Optional[Category] = None
    photoUrls: List[str] = Field(
        ...,
        description='Photo urls.',
        example=['http://example.com/photo.png', 'http://example.com/photo2', 'png'],
    )
    tags: Optional[List[Tag]] = None
    status: Optional[Status1] = Field(
        None, description='pet status in the store', example='available'
    )


class ApiResponse(BaseModel):
    code: Optional[int] = Field(None, description='Code', example=123)
    type: Optional[str] = Field(
        None, description='Response type', example='responsetype'
    )
    message: Optional[str] = Field(None, description='The message.', example='Message.')


class Status2(Enum):
    available = 'available'
    pending = 'pending'
    sold = 'sold'


class Status3(Enum):
    available = 'available'
    pending = 'pending'
    sold = 'sold'


